spring:
  profiles:
    active: default
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor
    username: root
    password: root #12345678
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8085
logging:
  level:
    org:
      springframework:
        security: WARN